#!/bin/bash

height=250
gap=4
search=40
out=600

set -x

./ttfcompile /usr/share/fonts/truetype/freefont/FreeSans.ttf $height $gap $search $out -o=../free/sans
./ttfcompile /usr/share/fonts/truetype/freefont/FreeMono.ttf $height $gap $search $out -o=../free/mono
./ttfcompile /usr/share/fonts/truetype/freefont/FreeSerif.ttf $height $gap $search $out -o=../free/serif
./ttfcompile /usr/share/fonts/truetype/freefont/FreeSansOblique.ttf $height $gap $search $out -o=../free/sansoblique
./ttfcompile /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf $height $gap $search $out -o=../dejavu/sans
./ttfcompile /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf $height $gap $search $out -o=../dejavu/sansmono
./ttfcompile /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf $height $gap $search $out -o=../dejavu/serif
./ttfcompile /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf $height $gap $search $out -o=../dejavu/sanscondensed
./ttfcompile /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed.ttf $height $gap $search $out -o=../dejavu/serifcondensed
