#!/bin/bash

height=150
gap=1
search=30
out=512

set -x

./gl3font /usr/share/fonts/truetype/freefont/FreeSans.ttf $height $gap $search $out -o=../free/sans
./gl3font /usr/share/fonts/truetype/freefont/FreeMono.ttf $height $gap $search $out -o=../free/mono
./gl3font /usr/share/fonts/truetype/freefont/FreeSerif.ttf $height $gap $search $out -o=../free/serif
./gl3font /usr/share/fonts/truetype/freefont/FreeSansOblique.ttf $height $gap $search $out -o=../free/sansoblique
./gl3font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf $height $gap $search $out -o=../dejavu/sans
./gl3font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf $height $gap $search $out -o=../dejavu/sansmono
./gl3font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf $height $gap $search $out -o=../dejavu/serif
./gl3font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf $height $gap $search $out -o=../dejavu/sanscondensed
./gl3font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed.ttf $height $gap $search $out -o=../dejavu/serifcondensed
