#!/bin/bash

if [ $# -eq 0 ]
then
    echo "usage:"
    echo "   ttf2json font.ttf outputname maxpixelsize miplevels"
    echo "example:"
    echo "   ttf2json /usr/share/fonts/truetype/freefont/FreeSans.ttf freesans 96 5"
    echo "generates freesans.png, freesans2.png -> freesans5.png using pixel sizes 96 48 24 12 6 and freesans.json"
    exit 0
else

    file=$1
    out=$2
    maxsize=$3
    levels=$4

    ./gl3font $file $maxsize -o=$out -data

    size=$(($maxsize/2))
    for i in $(seq 2 $levels)
    do
        ./gl3font $file $size -o=$out${i}
        size=$(($size/2))
    done
fi
